[versions]
agp = "8.13.0"
core = "1.6.1"
flinger = "1.3.0"
junit = "4.13.2"
kotlin = "2.2.20"
coreKtx = "1.13.1"
activityCompose = "1.9.3"
composeBom = "2025.04.00"
appcompat = "1.7.1"
material = "1.7.8"
mockitoCore = "5.20.0"
truth = "1.4.5"
navigationRuntimeKtx = "2.9.6"
navigationCompose = "2.8.9"

[libraries]
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
flinger = { module = "com.github.iamjosephmj:flinger", version.ref = "flinger" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
